/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import {expect, mergeTests} from '@playwright/test';

import {PortalToolsRestBuilderTestClient} from '../../../../util/portal-tools-rest-builder-test-client-js/src/main/resources/META-INF/resources/node';
import {apiHelpersTest} from '../../fixtures/apiHelpersTest';
import {loginTest} from '../../fixtures/loginTest';

const test = mergeTests(loginTest(), apiHelpersTest);

test('can use the autogenerated js client', async ({apiHelpers}) => {
	const portalToolsRestBuilderTestClient = await apiHelpers.buildRestClient(
		PortalToolsRestBuilderTestClient
	);

	const testEntity =
		await portalToolsRestBuilderTestClient.testEntity.postTestEntity({
			requestBody: {name: 'test', type: 'ChildTestEntity1'},
		});

	expect(testEntity).toMatchObject({name: 'test'});

	expect(
		await portalToolsRestBuilderTestClient.testEntity.getTestEntity({
			testEntityId: testEntity.id,
		})
	).toMatchObject(testEntity);

	const entitiesPage =
		await portalToolsRestBuilderTestClient.testEntity.getTestEntitiesPage();

	expect(entitiesPage.items).toContainEqual(testEntity);
	expect(entitiesPage.page).toBeGreaterThanOrEqual(1);
	expect(entitiesPage.totalCount).toBeGreaterThanOrEqual(1);
});
