/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fulfilment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FulfilmentRequest service. Represents a row in the &quot;FulfilmentRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.fulfilment.model.impl.FulfilmentRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.fulfilment.model.impl.FulfilmentRequestImpl</code>.
 * </p>
 *
 * @author Riccardo Alberti
 * @see FulfilmentRequest
 * @generated
 */
@ProviderType
public interface FulfilmentRequestModel
	extends AuditedModel, BaseModel<FulfilmentRequest>, MVCCModel, ShardedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fulfilment request model instance should use the {@link FulfilmentRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this fulfilment request.
	 *
	 * @return the primary key of this fulfilment request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fulfilment request.
	 *
	 * @param primaryKey the primary key of this fulfilment request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this fulfilment request.
	 *
	 * @return the mvcc version of this fulfilment request
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this fulfilment request.
	 *
	 * @param mvccVersion the mvcc version of this fulfilment request
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the external reference code of this fulfilment request.
	 *
	 * @return the external reference code of this fulfilment request
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this fulfilment request.
	 *
	 * @param externalReferenceCode the external reference code of this fulfilment request
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the fulfilment request ID of this fulfilment request.
	 *
	 * @return the fulfilment request ID of this fulfilment request
	 */
	public long getFulfilmentRequestId();

	/**
	 * Sets the fulfilment request ID of this fulfilment request.
	 *
	 * @param fulfilmentRequestId the fulfilment request ID of this fulfilment request
	 */
	public void setFulfilmentRequestId(long fulfilmentRequestId);

	/**
	 * Returns the company ID of this fulfilment request.
	 *
	 * @return the company ID of this fulfilment request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fulfilment request.
	 *
	 * @param companyId the company ID of this fulfilment request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fulfilment request.
	 *
	 * @return the user ID of this fulfilment request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fulfilment request.
	 *
	 * @param userId the user ID of this fulfilment request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fulfilment request.
	 *
	 * @return the user uuid of this fulfilment request
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fulfilment request.
	 *
	 * @param userUuid the user uuid of this fulfilment request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fulfilment request.
	 *
	 * @return the user name of this fulfilment request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fulfilment request.
	 *
	 * @param userName the user name of this fulfilment request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fulfilment request.
	 *
	 * @return the create date of this fulfilment request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fulfilment request.
	 *
	 * @param createDate the create date of this fulfilment request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fulfilment request.
	 *
	 * @return the modified date of this fulfilment request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fulfilment request.
	 *
	 * @param modifiedDate the modified date of this fulfilment request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the end date of this fulfilment request.
	 *
	 * @return the end date of this fulfilment request
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this fulfilment request.
	 *
	 * @param endDate the end date of this fulfilment request
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the original fulfilment request of this fulfilment request.
	 *
	 * @return the original fulfilment request of this fulfilment request
	 */
	@AutoEscape
	public String getOriginalFulfilmentRequest();

	/**
	 * Sets the original fulfilment request of this fulfilment request.
	 *
	 * @param originalFulfilmentRequest the original fulfilment request of this fulfilment request
	 */
	public void setOriginalFulfilmentRequest(String originalFulfilmentRequest);

	/**
	 * Returns the input parameters of this fulfilment request.
	 *
	 * @return the input parameters of this fulfilment request
	 */
	@AutoEscape
	public String getInputParameters();

	/**
	 * Sets the input parameters of this fulfilment request.
	 *
	 * @param inputParameters the input parameters of this fulfilment request
	 */
	public void setInputParameters(String inputParameters);

	/**
	 * Returns the output parameters of this fulfilment request.
	 *
	 * @return the output parameters of this fulfilment request
	 */
	@AutoEscape
	public String getOutputParameters();

	/**
	 * Sets the output parameters of this fulfilment request.
	 *
	 * @param outputParameters the output parameters of this fulfilment request
	 */
	public void setOutputParameters(String outputParameters);

	/**
	 * Returns the reply to of this fulfilment request.
	 *
	 * @return the reply to of this fulfilment request
	 */
	@AutoEscape
	public String getReplyTo();

	/**
	 * Sets the reply to of this fulfilment request.
	 *
	 * @param replyTo the reply to of this fulfilment request
	 */
	public void setReplyTo(String replyTo);

	/**
	 * Returns the start date of this fulfilment request.
	 *
	 * @return the start date of this fulfilment request
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this fulfilment request.
	 *
	 * @param startDate the start date of this fulfilment request
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the type of this fulfilment request.
	 *
	 * @return the type of this fulfilment request
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this fulfilment request.
	 *
	 * @param type the type of this fulfilment request
	 */
	public void setType(String type);

	/**
	 * Returns the workflow definition link ID of this fulfilment request.
	 *
	 * @return the workflow definition link ID of this fulfilment request
	 */
	public long getWorkflowDefinitionLinkId();

	/**
	 * Sets the workflow definition link ID of this fulfilment request.
	 *
	 * @param workflowDefinitionLinkId the workflow definition link ID of this fulfilment request
	 */
	public void setWorkflowDefinitionLinkId(long workflowDefinitionLinkId);

	/**
	 * Returns the status of this fulfilment request.
	 *
	 * @return the status of this fulfilment request
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this fulfilment request.
	 *
	 * @param status the status of this fulfilment request
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this fulfilment request.
	 *
	 * @return the status by user ID of this fulfilment request
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this fulfilment request.
	 *
	 * @param statusByUserId the status by user ID of this fulfilment request
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this fulfilment request.
	 *
	 * @return the status by user uuid of this fulfilment request
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this fulfilment request.
	 *
	 * @param statusByUserUuid the status by user uuid of this fulfilment request
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this fulfilment request.
	 *
	 * @return the status by user name of this fulfilment request
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this fulfilment request.
	 *
	 * @param statusByUserName the status by user name of this fulfilment request
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this fulfilment request.
	 *
	 * @return the status date of this fulfilment request
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this fulfilment request.
	 *
	 * @param statusDate the status date of this fulfilment request
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this fulfilment request is approved.
	 *
	 * @return <code>true</code> if this fulfilment request is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this fulfilment request is denied.
	 *
	 * @return <code>true</code> if this fulfilment request is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this fulfilment request is a draft.
	 *
	 * @return <code>true</code> if this fulfilment request is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this fulfilment request is expired.
	 *
	 * @return <code>true</code> if this fulfilment request is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this fulfilment request is inactive.
	 *
	 * @return <code>true</code> if this fulfilment request is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this fulfilment request is incomplete.
	 *
	 * @return <code>true</code> if this fulfilment request is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this fulfilment request is pending.
	 *
	 * @return <code>true</code> if this fulfilment request is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this fulfilment request is scheduled.
	 *
	 * @return <code>true</code> if this fulfilment request is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public FulfilmentRequest cloneWithOriginalValues();

}