/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fulfilment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FulfilmentTask service. Represents a row in the &quot;FulfilmentTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.fulfilment.model.impl.FulfilmentTaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.fulfilment.model.impl.FulfilmentTaskImpl</code>.
 * </p>
 *
 * @author Riccardo Alberti
 * @see FulfilmentTask
 * @generated
 */
@ProviderType
public interface FulfilmentTaskModel
	extends AuditedModel, BaseModel<FulfilmentTask>, MVCCModel, ShardedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fulfilment task model instance should use the {@link FulfilmentTask} interface instead.
	 */

	/**
	 * Returns the primary key of this fulfilment task.
	 *
	 * @return the primary key of this fulfilment task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fulfilment task.
	 *
	 * @param primaryKey the primary key of this fulfilment task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this fulfilment task.
	 *
	 * @return the mvcc version of this fulfilment task
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this fulfilment task.
	 *
	 * @param mvccVersion the mvcc version of this fulfilment task
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the fulfilment task ID of this fulfilment task.
	 *
	 * @return the fulfilment task ID of this fulfilment task
	 */
	public long getFulfilmentTaskId();

	/**
	 * Sets the fulfilment task ID of this fulfilment task.
	 *
	 * @param fulfilmentTaskId the fulfilment task ID of this fulfilment task
	 */
	public void setFulfilmentTaskId(long fulfilmentTaskId);

	/**
	 * Returns the company ID of this fulfilment task.
	 *
	 * @return the company ID of this fulfilment task
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fulfilment task.
	 *
	 * @param companyId the company ID of this fulfilment task
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fulfilment task.
	 *
	 * @return the user ID of this fulfilment task
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fulfilment task.
	 *
	 * @param userId the user ID of this fulfilment task
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fulfilment task.
	 *
	 * @return the user uuid of this fulfilment task
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fulfilment task.
	 *
	 * @param userUuid the user uuid of this fulfilment task
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fulfilment task.
	 *
	 * @return the user name of this fulfilment task
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fulfilment task.
	 *
	 * @param userName the user name of this fulfilment task
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fulfilment task.
	 *
	 * @return the create date of this fulfilment task
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fulfilment task.
	 *
	 * @param createDate the create date of this fulfilment task
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fulfilment task.
	 *
	 * @return the modified date of this fulfilment task
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fulfilment task.
	 *
	 * @param modifiedDate the modified date of this fulfilment task
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the correlation ID of this fulfilment task.
	 *
	 * @return the correlation ID of this fulfilment task
	 */
	public long getCorrelationId();

	/**
	 * Sets the correlation ID of this fulfilment task.
	 *
	 * @param correlationId the correlation ID of this fulfilment task
	 */
	public void setCorrelationId(long correlationId);

	/**
	 * Returns the end date of this fulfilment task.
	 *
	 * @return the end date of this fulfilment task
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this fulfilment task.
	 *
	 * @param endDate the end date of this fulfilment task
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the fulfilment request ID of this fulfilment task.
	 *
	 * @return the fulfilment request ID of this fulfilment task
	 */
	public long getFulfilmentRequestId();

	/**
	 * Sets the fulfilment request ID of this fulfilment task.
	 *
	 * @param fulfilmentRequestId the fulfilment request ID of this fulfilment task
	 */
	public void setFulfilmentRequestId(long fulfilmentRequestId);

	/**
	 * Returns the index of this fulfilment task.
	 *
	 * @return the index of this fulfilment task
	 */
	public long getIndex();

	/**
	 * Sets the index of this fulfilment task.
	 *
	 * @param index the index of this fulfilment task
	 */
	public void setIndex(long index);

	/**
	 * Returns the input parameters of this fulfilment task.
	 *
	 * @return the input parameters of this fulfilment task
	 */
	@AutoEscape
	public String getInputParameters();

	/**
	 * Sets the input parameters of this fulfilment task.
	 *
	 * @param inputParameters the input parameters of this fulfilment task
	 */
	public void setInputParameters(String inputParameters);

	/**
	 * Returns the output parameters of this fulfilment task.
	 *
	 * @return the output parameters of this fulfilment task
	 */
	@AutoEscape
	public String getOutputParameters();

	/**
	 * Sets the output parameters of this fulfilment task.
	 *
	 * @param outputParameters the output parameters of this fulfilment task
	 */
	public void setOutputParameters(String outputParameters);

	/**
	 * Returns the start date of this fulfilment task.
	 *
	 * @return the start date of this fulfilment task
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this fulfilment task.
	 *
	 * @param startDate the start date of this fulfilment task
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the type of this fulfilment task.
	 *
	 * @return the type of this fulfilment task
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this fulfilment task.
	 *
	 * @param type the type of this fulfilment task
	 */
	public void setType(String type);

	/**
	 * Returns the status of this fulfilment task.
	 *
	 * @return the status of this fulfilment task
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this fulfilment task.
	 *
	 * @param status the status of this fulfilment task
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this fulfilment task.
	 *
	 * @return the status by user ID of this fulfilment task
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this fulfilment task.
	 *
	 * @param statusByUserId the status by user ID of this fulfilment task
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this fulfilment task.
	 *
	 * @return the status by user uuid of this fulfilment task
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this fulfilment task.
	 *
	 * @param statusByUserUuid the status by user uuid of this fulfilment task
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this fulfilment task.
	 *
	 * @return the status by user name of this fulfilment task
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this fulfilment task.
	 *
	 * @param statusByUserName the status by user name of this fulfilment task
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this fulfilment task.
	 *
	 * @return the status date of this fulfilment task
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this fulfilment task.
	 *
	 * @param statusDate the status date of this fulfilment task
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this fulfilment task is approved.
	 *
	 * @return <code>true</code> if this fulfilment task is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this fulfilment task is denied.
	 *
	 * @return <code>true</code> if this fulfilment task is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this fulfilment task is a draft.
	 *
	 * @return <code>true</code> if this fulfilment task is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this fulfilment task is expired.
	 *
	 * @return <code>true</code> if this fulfilment task is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this fulfilment task is inactive.
	 *
	 * @return <code>true</code> if this fulfilment task is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this fulfilment task is incomplete.
	 *
	 * @return <code>true</code> if this fulfilment task is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this fulfilment task is pending.
	 *
	 * @return <code>true</code> if this fulfilment task is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this fulfilment task is scheduled.
	 *
	 * @return <code>true</code> if this fulfilment task is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public FulfilmentTask cloneWithOriginalValues();

}