/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.qualification.model.impl;

import com.liferay.commerce.qualification.model.CommerceQualificationRel;
import com.liferay.commerce.qualification.model.CommerceQualificationRelModel;
import com.liferay.commerce.qualification.model.CommerceQualificationRelSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceQualificationRel service. Represents a row in the &quot;CommerceQualificationRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommerceQualificationRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceQualificationRelImpl}.
 * </p>
 *
 * @author Riccardo Alberti
 * @see CommerceQualificationRelImpl
 * @generated
 */
@JSON(strict = true)
public class CommerceQualificationRelModelImpl
	extends BaseModelImpl<CommerceQualificationRel>
	implements CommerceQualificationRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce qualification rel model instance should use the <code>CommerceQualificationRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommerceQualificationRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"commerceQualificationRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"sourceClassNameId", Types.BIGINT},
		{"sourceClassPK", Types.BIGINT}, {"targetClassNameId", Types.BIGINT},
		{"targetClassPK", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceQualificationRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("sourceClassNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sourceClassPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("targetClassNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("targetClassPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommerceQualificationRel (mvccVersion LONG default 0 not null,commerceQualificationRelId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,sourceClassNameId LONG,sourceClassPK LONG,targetClassNameId LONG,targetClassPK LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table CommerceQualificationRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceQualificationRel.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommerceQualificationRel.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SOURCECLASSNAMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SOURCECLASSPK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TARGETCLASSNAMEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TARGETCLASSPK_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static CommerceQualificationRel toModel(
		CommerceQualificationRelSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		CommerceQualificationRel model = new CommerceQualificationRelImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setCommerceQualificationRelId(
			soapModel.getCommerceQualificationRelId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setSourceClassNameId(soapModel.getSourceClassNameId());
		model.setSourceClassPK(soapModel.getSourceClassPK());
		model.setTargetClassNameId(soapModel.getTargetClassNameId());
		model.setTargetClassPK(soapModel.getTargetClassPK());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<CommerceQualificationRel> toModels(
		CommerceQualificationRelSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CommerceQualificationRel> models =
			new ArrayList<CommerceQualificationRel>(soapModels.length);

		for (CommerceQualificationRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CommerceQualificationRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceQualificationRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceQualificationRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceQualificationRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceQualificationRel.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceQualificationRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceQualificationRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommerceQualificationRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceQualificationRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommerceQualificationRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceQualificationRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceQualificationRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceQualificationRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceQualificationRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceQualificationRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CommerceQualificationRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CommerceQualificationRel.class.getClassLoader(),
			CommerceQualificationRel.class, ModelWrapper.class);

		try {
			Constructor<CommerceQualificationRel> constructor =
				(Constructor<CommerceQualificationRel>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CommerceQualificationRel, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CommerceQualificationRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommerceQualificationRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CommerceQualificationRel, Object>>();
		Map<String, BiConsumer<CommerceQualificationRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CommerceQualificationRel, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", CommerceQualificationRel::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<CommerceQualificationRel, Long>)
				CommerceQualificationRel::setMvccVersion);
		attributeGetterFunctions.put(
			"commerceQualificationRelId",
			CommerceQualificationRel::getCommerceQualificationRelId);
		attributeSetterBiConsumers.put(
			"commerceQualificationRelId",
			(BiConsumer<CommerceQualificationRel, Long>)
				CommerceQualificationRel::setCommerceQualificationRelId);
		attributeGetterFunctions.put(
			"companyId", CommerceQualificationRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CommerceQualificationRel, Long>)
				CommerceQualificationRel::setCompanyId);
		attributeGetterFunctions.put(
			"userId", CommerceQualificationRel::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CommerceQualificationRel, Long>)
				CommerceQualificationRel::setUserId);
		attributeGetterFunctions.put(
			"userName", CommerceQualificationRel::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<CommerceQualificationRel, String>)
				CommerceQualificationRel::setUserName);
		attributeGetterFunctions.put(
			"createDate", CommerceQualificationRel::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CommerceQualificationRel, Date>)
				CommerceQualificationRel::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", CommerceQualificationRel::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CommerceQualificationRel, Date>)
				CommerceQualificationRel::setModifiedDate);
		attributeGetterFunctions.put(
			"sourceClassNameId",
			CommerceQualificationRel::getSourceClassNameId);
		attributeSetterBiConsumers.put(
			"sourceClassNameId",
			(BiConsumer<CommerceQualificationRel, Long>)
				CommerceQualificationRel::setSourceClassNameId);
		attributeGetterFunctions.put(
			"sourceClassPK", CommerceQualificationRel::getSourceClassPK);
		attributeSetterBiConsumers.put(
			"sourceClassPK",
			(BiConsumer<CommerceQualificationRel, Long>)
				CommerceQualificationRel::setSourceClassPK);
		attributeGetterFunctions.put(
			"targetClassNameId",
			CommerceQualificationRel::getTargetClassNameId);
		attributeSetterBiConsumers.put(
			"targetClassNameId",
			(BiConsumer<CommerceQualificationRel, Long>)
				CommerceQualificationRel::setTargetClassNameId);
		attributeGetterFunctions.put(
			"targetClassPK", CommerceQualificationRel::getTargetClassPK);
		attributeSetterBiConsumers.put(
			"targetClassPK",
			(BiConsumer<CommerceQualificationRel, Long>)
				CommerceQualificationRel::setTargetClassPK);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCommerceQualificationRelId() {
		return _commerceQualificationRelId;
	}

	@Override
	public void setCommerceQualificationRelId(long commerceQualificationRelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceQualificationRelId = commerceQualificationRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getSourceClassNameId() {
		return _sourceClassNameId;
	}

	@Override
	public void setSourceClassNameId(long sourceClassNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sourceClassNameId = sourceClassNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSourceClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("sourceClassNameId"));
	}

	@JSON
	@Override
	public long getSourceClassPK() {
		return _sourceClassPK;
	}

	@Override
	public void setSourceClassPK(long sourceClassPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sourceClassPK = sourceClassPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSourceClassPK() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("sourceClassPK"));
	}

	@JSON
	@Override
	public long getTargetClassNameId() {
		return _targetClassNameId;
	}

	@Override
	public void setTargetClassNameId(long targetClassNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_targetClassNameId = targetClassNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTargetClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("targetClassNameId"));
	}

	@JSON
	@Override
	public long getTargetClassPK() {
		return _targetClassPK;
	}

	@Override
	public void setTargetClassPK(long targetClassPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_targetClassPK = targetClassPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTargetClassPK() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("targetClassPK"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceQualificationRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceQualificationRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommerceQualificationRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceQualificationRelImpl commerceQualificationRelImpl =
			new CommerceQualificationRelImpl();

		commerceQualificationRelImpl.setMvccVersion(getMvccVersion());
		commerceQualificationRelImpl.setCommerceQualificationRelId(
			getCommerceQualificationRelId());
		commerceQualificationRelImpl.setCompanyId(getCompanyId());
		commerceQualificationRelImpl.setUserId(getUserId());
		commerceQualificationRelImpl.setUserName(getUserName());
		commerceQualificationRelImpl.setCreateDate(getCreateDate());
		commerceQualificationRelImpl.setModifiedDate(getModifiedDate());
		commerceQualificationRelImpl.setSourceClassNameId(
			getSourceClassNameId());
		commerceQualificationRelImpl.setSourceClassPK(getSourceClassPK());
		commerceQualificationRelImpl.setTargetClassNameId(
			getTargetClassNameId());
		commerceQualificationRelImpl.setTargetClassPK(getTargetClassPK());

		commerceQualificationRelImpl.resetOriginalValues();

		return commerceQualificationRelImpl;
	}

	@Override
	public CommerceQualificationRel cloneWithOriginalValues() {
		CommerceQualificationRelImpl commerceQualificationRelImpl =
			new CommerceQualificationRelImpl();

		commerceQualificationRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		commerceQualificationRelImpl.setCommerceQualificationRelId(
			this.<Long>getColumnOriginalValue("commerceQualificationRelId"));
		commerceQualificationRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		commerceQualificationRelImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		commerceQualificationRelImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		commerceQualificationRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		commerceQualificationRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		commerceQualificationRelImpl.setSourceClassNameId(
			this.<Long>getColumnOriginalValue("sourceClassNameId"));
		commerceQualificationRelImpl.setSourceClassPK(
			this.<Long>getColumnOriginalValue("sourceClassPK"));
		commerceQualificationRelImpl.setTargetClassNameId(
			this.<Long>getColumnOriginalValue("targetClassNameId"));
		commerceQualificationRelImpl.setTargetClassPK(
			this.<Long>getColumnOriginalValue("targetClassPK"));

		return commerceQualificationRelImpl;
	}

	@Override
	public int compareTo(CommerceQualificationRel commerceQualificationRel) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), commerceQualificationRel.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommerceQualificationRel)) {
			return false;
		}

		CommerceQualificationRel commerceQualificationRel =
			(CommerceQualificationRel)object;

		long primaryKey = commerceQualificationRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceQualificationRel> toCacheModel() {
		CommerceQualificationRelCacheModel commerceQualificationRelCacheModel =
			new CommerceQualificationRelCacheModel();

		commerceQualificationRelCacheModel.mvccVersion = getMvccVersion();

		commerceQualificationRelCacheModel.commerceQualificationRelId =
			getCommerceQualificationRelId();

		commerceQualificationRelCacheModel.companyId = getCompanyId();

		commerceQualificationRelCacheModel.userId = getUserId();

		commerceQualificationRelCacheModel.userName = getUserName();

		String userName = commerceQualificationRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceQualificationRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceQualificationRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			commerceQualificationRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceQualificationRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commerceQualificationRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commerceQualificationRelCacheModel.sourceClassNameId =
			getSourceClassNameId();

		commerceQualificationRelCacheModel.sourceClassPK = getSourceClassPK();

		commerceQualificationRelCacheModel.targetClassNameId =
			getTargetClassNameId();

		commerceQualificationRelCacheModel.targetClassPK = getTargetClassPK();

		return commerceQualificationRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceQualificationRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommerceQualificationRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceQualificationRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CommerceQualificationRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommerceQualificationRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommerceQualificationRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceQualificationRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((CommerceQualificationRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommerceQualificationRel>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _commerceQualificationRelId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _sourceClassNameId;
	private long _sourceClassPK;
	private long _targetClassNameId;
	private long _targetClassPK;

	public <T> T getColumnValue(String columnName) {
		Function<CommerceQualificationRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CommerceQualificationRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"commerceQualificationRelId", _commerceQualificationRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("sourceClassNameId", _sourceClassNameId);
		_columnOriginalValues.put("sourceClassPK", _sourceClassPK);
		_columnOriginalValues.put("targetClassNameId", _targetClassNameId);
		_columnOriginalValues.put("targetClassPK", _targetClassPK);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("commerceQualificationRelId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("sourceClassNameId", 128L);

		columnBitmasks.put("sourceClassPK", 256L);

		columnBitmasks.put("targetClassNameId", 512L);

		columnBitmasks.put("targetClassPK", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CommerceQualificationRel _escapedModel;

}