##
## Playwright
##

    playwright.test.project[playwright-js-tomcat90-mysql57-jdk8][relevant][object-rest-rule]=

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*][relevant][object-rest-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][object-rest-rule]=\
        **/object/object-rest-test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][object-rest-rule]=\
        **/object/object-rest-test/**/src/test/**/*Test.java

    test.batch.class.names.includes[relevant][object-rest-rule]=\
        **/headless-builder/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*][relevant][object-rest-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names == "Object Entries REST APIs") OR \
            (testray.main.component.name == "Object Entries REST APIs")\
        )

##
## Test Suites
##

    modified.files.includes[relevant][object-rest-rule]=**

    relevant.rule.names=\
        object-rest-rule

    test.batch.names[relevant][object-rest-rule]=\
        functional-tomcat90-mysql57,\
        modules-integration-mysql57-jdk8,\
        modules-unit-jdk8,\
        playwright-js-tomcat90-mysql57-jdk8

##
## Testray
##

    testray.main.component.name=Object Entries REST APIs