#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.object.lambda.rest.dto.v1_0.LambdaResponse
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Object.Lambda.REST)
osgi.jaxrs.resource=true