##
## Test Suites
##

    modified.files.includes[relevant][template-rule]=**

    relevant.rule.names=\
        template-rule

    test.batch.names[relevant][template-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][template-rule]=\
        apps/template/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][template-rule]=\
        apps/template/**/*Test.java

##
## Testray
##

    testray.main.component.name=Templates