/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.inventory.model.impl;

import com.liferay.commerce.inventory.model.CommerceInventoryWarehouseOrderTypeRel;
import com.liferay.commerce.inventory.model.CommerceInventoryWarehouseOrderTypeRelModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceInventoryWarehouseOrderTypeRel service. Represents a row in the &quot;CIWarehouseOrderTypeRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommerceInventoryWarehouseOrderTypeRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceInventoryWarehouseOrderTypeRelImpl}.
 * </p>
 *
 * @author Luca Pellizzon
 * @see CommerceInventoryWarehouseOrderTypeRelImpl
 * @generated
 */
@JSON(strict = true)
public class CommerceInventoryWarehouseOrderTypeRelModelImpl
	extends BaseModelImpl<CommerceInventoryWarehouseOrderTypeRel>
	implements CommerceInventoryWarehouseOrderTypeRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce inventory warehouse order type rel model instance should use the <code>CommerceInventoryWarehouseOrderTypeRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CIWarehouseOrderTypeRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"CIWarehouseOrderTypeRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"commerceInventoryWarehouseId", Types.BIGINT},
		{"commerceOrderTypeId", Types.BIGINT}, {"priority", Types.INTEGER},
		{"lastPublishDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CIWarehouseOrderTypeRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceInventoryWarehouseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceOrderTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CIWarehouseOrderTypeRel (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,CIWarehouseOrderTypeRelId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commerceInventoryWarehouseId LONG,commerceOrderTypeId LONG,priority INTEGER,lastPublishDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table CIWarehouseOrderTypeRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceInventoryWarehouseOrderTypeRel.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CIWarehouseOrderTypeRel.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCEINVENTORYWAREHOUSEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCEORDERTYPEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRIORITY_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.inventory.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.inventory.model.CommerceInventoryWarehouseOrderTypeRel"));

	public CommerceInventoryWarehouseOrderTypeRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceInventoryWarehouseOrderTypeRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceInventoryWarehouseOrderTypeRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceInventoryWarehouseOrderTypeRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceInventoryWarehouseOrderTypeRel.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceInventoryWarehouseOrderTypeRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String,
				 Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceInventoryWarehouseOrderTypeRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CommerceInventoryWarehouseOrderTypeRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceInventoryWarehouseOrderTypeRel)this,
					entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map
		<String, BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Object>>
			getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function
		<InvocationHandler, CommerceInventoryWarehouseOrderTypeRel>
			_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CommerceInventoryWarehouseOrderTypeRel.class.getClassLoader(),
			CommerceInventoryWarehouseOrderTypeRel.class, ModelWrapper.class);

		try {
			Constructor<CommerceInventoryWarehouseOrderTypeRel> constructor =
				(Constructor<CommerceInventoryWarehouseOrderTypeRel>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function
						 <CommerceInventoryWarehouseOrderTypeRel, Object>>();
		Map<String, BiConsumer<CommerceInventoryWarehouseOrderTypeRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String,
					 BiConsumer<CommerceInventoryWarehouseOrderTypeRel, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion",
			CommerceInventoryWarehouseOrderTypeRel::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Long>)
				CommerceInventoryWarehouseOrderTypeRel::setMvccVersion);
		attributeGetterFunctions.put(
			"uuid", CommerceInventoryWarehouseOrderTypeRel::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, String>)
				CommerceInventoryWarehouseOrderTypeRel::setUuid);
		attributeGetterFunctions.put(
			"commerceInventoryWarehouseOrderTypeRelId",
			CommerceInventoryWarehouseOrderTypeRel::
				getCommerceInventoryWarehouseOrderTypeRelId);
		attributeSetterBiConsumers.put(
			"commerceInventoryWarehouseOrderTypeRelId",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Long>)
				CommerceInventoryWarehouseOrderTypeRel::
					setCommerceInventoryWarehouseOrderTypeRelId);
		attributeGetterFunctions.put(
			"companyId", CommerceInventoryWarehouseOrderTypeRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Long>)
				CommerceInventoryWarehouseOrderTypeRel::setCompanyId);
		attributeGetterFunctions.put(
			"userId", CommerceInventoryWarehouseOrderTypeRel::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Long>)
				CommerceInventoryWarehouseOrderTypeRel::setUserId);
		attributeGetterFunctions.put(
			"userName", CommerceInventoryWarehouseOrderTypeRel::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, String>)
				CommerceInventoryWarehouseOrderTypeRel::setUserName);
		attributeGetterFunctions.put(
			"createDate",
			CommerceInventoryWarehouseOrderTypeRel::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Date>)
				CommerceInventoryWarehouseOrderTypeRel::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate",
			CommerceInventoryWarehouseOrderTypeRel::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Date>)
				CommerceInventoryWarehouseOrderTypeRel::setModifiedDate);
		attributeGetterFunctions.put(
			"commerceInventoryWarehouseId",
			CommerceInventoryWarehouseOrderTypeRel::
				getCommerceInventoryWarehouseId);
		attributeSetterBiConsumers.put(
			"commerceInventoryWarehouseId",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Long>)
				CommerceInventoryWarehouseOrderTypeRel::
					setCommerceInventoryWarehouseId);
		attributeGetterFunctions.put(
			"commerceOrderTypeId",
			CommerceInventoryWarehouseOrderTypeRel::getCommerceOrderTypeId);
		attributeSetterBiConsumers.put(
			"commerceOrderTypeId",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Long>)
				CommerceInventoryWarehouseOrderTypeRel::setCommerceOrderTypeId);
		attributeGetterFunctions.put(
			"priority", CommerceInventoryWarehouseOrderTypeRel::getPriority);
		attributeSetterBiConsumers.put(
			"priority",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Integer>)
				CommerceInventoryWarehouseOrderTypeRel::setPriority);
		attributeGetterFunctions.put(
			"lastPublishDate",
			CommerceInventoryWarehouseOrderTypeRel::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<CommerceInventoryWarehouseOrderTypeRel, Date>)
				CommerceInventoryWarehouseOrderTypeRel::setLastPublishDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCommerceInventoryWarehouseOrderTypeRelId() {
		return _commerceInventoryWarehouseOrderTypeRelId;
	}

	@Override
	public void setCommerceInventoryWarehouseOrderTypeRelId(
		long commerceInventoryWarehouseOrderTypeRelId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceInventoryWarehouseOrderTypeRelId =
			commerceInventoryWarehouseOrderTypeRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCommerceInventoryWarehouseId() {
		return _commerceInventoryWarehouseId;
	}

	@Override
	public void setCommerceInventoryWarehouseId(
		long commerceInventoryWarehouseId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceInventoryWarehouseId = commerceInventoryWarehouseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommerceInventoryWarehouseId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commerceInventoryWarehouseId"));
	}

	@JSON
	@Override
	public long getCommerceOrderTypeId() {
		return _commerceOrderTypeId;
	}

	@Override
	public void setCommerceOrderTypeId(long commerceOrderTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceOrderTypeId = commerceOrderTypeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommerceOrderTypeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commerceOrderTypeId"));
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priority = priority;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastPublishDate = lastPublishDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				CommerceInventoryWarehouseOrderTypeRel.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(),
			CommerceInventoryWarehouseOrderTypeRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceInventoryWarehouseOrderTypeRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommerceInventoryWarehouseOrderTypeRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceInventoryWarehouseOrderTypeRelImpl
			commerceInventoryWarehouseOrderTypeRelImpl =
				new CommerceInventoryWarehouseOrderTypeRelImpl();

		commerceInventoryWarehouseOrderTypeRelImpl.setMvccVersion(
			getMvccVersion());
		commerceInventoryWarehouseOrderTypeRelImpl.setUuid(getUuid());
		commerceInventoryWarehouseOrderTypeRelImpl.
			setCommerceInventoryWarehouseOrderTypeRelId(
				getCommerceInventoryWarehouseOrderTypeRelId());
		commerceInventoryWarehouseOrderTypeRelImpl.setCompanyId(getCompanyId());
		commerceInventoryWarehouseOrderTypeRelImpl.setUserId(getUserId());
		commerceInventoryWarehouseOrderTypeRelImpl.setUserName(getUserName());
		commerceInventoryWarehouseOrderTypeRelImpl.setCreateDate(
			getCreateDate());
		commerceInventoryWarehouseOrderTypeRelImpl.setModifiedDate(
			getModifiedDate());
		commerceInventoryWarehouseOrderTypeRelImpl.
			setCommerceInventoryWarehouseId(getCommerceInventoryWarehouseId());
		commerceInventoryWarehouseOrderTypeRelImpl.setCommerceOrderTypeId(
			getCommerceOrderTypeId());
		commerceInventoryWarehouseOrderTypeRelImpl.setPriority(getPriority());
		commerceInventoryWarehouseOrderTypeRelImpl.setLastPublishDate(
			getLastPublishDate());

		commerceInventoryWarehouseOrderTypeRelImpl.resetOriginalValues();

		return commerceInventoryWarehouseOrderTypeRelImpl;
	}

	@Override
	public CommerceInventoryWarehouseOrderTypeRel cloneWithOriginalValues() {
		CommerceInventoryWarehouseOrderTypeRelImpl
			commerceInventoryWarehouseOrderTypeRelImpl =
				new CommerceInventoryWarehouseOrderTypeRelImpl();

		commerceInventoryWarehouseOrderTypeRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		commerceInventoryWarehouseOrderTypeRelImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		commerceInventoryWarehouseOrderTypeRelImpl.
			setCommerceInventoryWarehouseOrderTypeRelId(
				this.<Long>getColumnOriginalValue("CIWarehouseOrderTypeRelId"));
		commerceInventoryWarehouseOrderTypeRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		commerceInventoryWarehouseOrderTypeRelImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		commerceInventoryWarehouseOrderTypeRelImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		commerceInventoryWarehouseOrderTypeRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		commerceInventoryWarehouseOrderTypeRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		commerceInventoryWarehouseOrderTypeRelImpl.
			setCommerceInventoryWarehouseId(
				this.<Long>getColumnOriginalValue(
					"commerceInventoryWarehouseId"));
		commerceInventoryWarehouseOrderTypeRelImpl.setCommerceOrderTypeId(
			this.<Long>getColumnOriginalValue("commerceOrderTypeId"));
		commerceInventoryWarehouseOrderTypeRelImpl.setPriority(
			this.<Integer>getColumnOriginalValue("priority"));
		commerceInventoryWarehouseOrderTypeRelImpl.setLastPublishDate(
			this.<Date>getColumnOriginalValue("lastPublishDate"));

		return commerceInventoryWarehouseOrderTypeRelImpl;
	}

	@Override
	public int compareTo(
		CommerceInventoryWarehouseOrderTypeRel
			commerceInventoryWarehouseOrderTypeRel) {

		int value = 0;

		if (getPriority() <
				commerceInventoryWarehouseOrderTypeRel.getPriority()) {

			value = -1;
		}
		else if (getPriority() >
					commerceInventoryWarehouseOrderTypeRel.getPriority()) {

			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommerceInventoryWarehouseOrderTypeRel)) {
			return false;
		}

		CommerceInventoryWarehouseOrderTypeRel
			commerceInventoryWarehouseOrderTypeRel =
				(CommerceInventoryWarehouseOrderTypeRel)object;

		long primaryKey =
			commerceInventoryWarehouseOrderTypeRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceInventoryWarehouseOrderTypeRel> toCacheModel() {
		CommerceInventoryWarehouseOrderTypeRelCacheModel
			commerceInventoryWarehouseOrderTypeRelCacheModel =
				new CommerceInventoryWarehouseOrderTypeRelCacheModel();

		commerceInventoryWarehouseOrderTypeRelCacheModel.mvccVersion =
			getMvccVersion();

		commerceInventoryWarehouseOrderTypeRelCacheModel.uuid = getUuid();

		String uuid = commerceInventoryWarehouseOrderTypeRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commerceInventoryWarehouseOrderTypeRelCacheModel.uuid = null;
		}

		commerceInventoryWarehouseOrderTypeRelCacheModel.
			commerceInventoryWarehouseOrderTypeRelId =
				getCommerceInventoryWarehouseOrderTypeRelId();

		commerceInventoryWarehouseOrderTypeRelCacheModel.companyId =
			getCompanyId();

		commerceInventoryWarehouseOrderTypeRelCacheModel.userId = getUserId();

		commerceInventoryWarehouseOrderTypeRelCacheModel.userName =
			getUserName();

		String userName =
			commerceInventoryWarehouseOrderTypeRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceInventoryWarehouseOrderTypeRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceInventoryWarehouseOrderTypeRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			commerceInventoryWarehouseOrderTypeRelCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceInventoryWarehouseOrderTypeRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commerceInventoryWarehouseOrderTypeRelCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		commerceInventoryWarehouseOrderTypeRelCacheModel.
			commerceInventoryWarehouseId = getCommerceInventoryWarehouseId();

		commerceInventoryWarehouseOrderTypeRelCacheModel.commerceOrderTypeId =
			getCommerceOrderTypeId();

		commerceInventoryWarehouseOrderTypeRelCacheModel.priority =
			getPriority();

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			commerceInventoryWarehouseOrderTypeRelCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			commerceInventoryWarehouseOrderTypeRelCacheModel.lastPublishDate =
				Long.MIN_VALUE;
		}

		return commerceInventoryWarehouseOrderTypeRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String,
				 Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceInventoryWarehouseOrderTypeRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CommerceInventoryWarehouseOrderTypeRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry
				<String,
				 Function<CommerceInventoryWarehouseOrderTypeRel, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceInventoryWarehouseOrderTypeRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(CommerceInventoryWarehouseOrderTypeRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommerceInventoryWarehouseOrderTypeRel>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _mvccVersion;
	private String _uuid;
	private long _commerceInventoryWarehouseOrderTypeRelId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commerceInventoryWarehouseId;
	private long _commerceOrderTypeId;
	private int _priority;
	private Date _lastPublishDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CommerceInventoryWarehouseOrderTypeRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CommerceInventoryWarehouseOrderTypeRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"CIWarehouseOrderTypeRelId",
			_commerceInventoryWarehouseOrderTypeRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"commerceInventoryWarehouseId", _commerceInventoryWarehouseId);
		_columnOriginalValues.put("commerceOrderTypeId", _commerceOrderTypeId);
		_columnOriginalValues.put("priority", _priority);
		_columnOriginalValues.put("lastPublishDate", _lastPublishDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"CIWarehouseOrderTypeRelId",
			"commerceInventoryWarehouseOrderTypeRelId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("CIWarehouseOrderTypeRelId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("commerceInventoryWarehouseId", 256L);

		columnBitmasks.put("commerceOrderTypeId", 512L);

		columnBitmasks.put("priority", 1024L);

		columnBitmasks.put("lastPublishDate", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CommerceInventoryWarehouseOrderTypeRel _escapedModel;

}