##
## Test Suites
##

    modified.files.includes[relevant][liferay-customer-workspace-rule]=**

    playwright.test.project[relevant][liferay-customer-workspace-rule][playwright-js-tomcat90-mysql57]=\
        customer

    relevant.rule.names=\
        liferay-customer-workspace-rule

    test.batch.names[relevant][liferay-customer-workspace-rule]=\
        playwright-js-tomcat90-mysql57

##
## Testray
##

    testray.main.component.name=Liferay Customer Workspace