/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fulfilment.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.fulfilment.model.FulfilmentRequest;
import com.liferay.fulfilment.model.FulfilmentRequestModel;
import com.liferay.fulfilment.model.FulfilmentRequestSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FulfilmentRequest service. Represents a row in the &quot;FulfilmentRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FulfilmentRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FulfilmentRequestImpl}.
 * </p>
 *
 * @author Riccardo Alberti
 * @see FulfilmentRequestImpl
 * @generated
 */
@JSON(strict = true)
public class FulfilmentRequestModelImpl
	extends BaseModelImpl<FulfilmentRequest> implements FulfilmentRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fulfilment request model instance should use the <code>FulfilmentRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "FulfilmentRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"externalReferenceCode", Types.VARCHAR},
		{"fulfilmentRequestId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}, {"originalFulfilmentRequest", Types.CLOB},
		{"inputParameters", Types.CLOB}, {"outputParameters", Types.CLOB},
		{"replyTo", Types.VARCHAR}, {"startDate", Types.TIMESTAMP},
		{"type_", Types.VARCHAR}, {"workflowDefinitionLinkId", Types.BIGINT},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fulfilmentRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("originalFulfilmentRequest", Types.CLOB);
		TABLE_COLUMNS_MAP.put("inputParameters", Types.CLOB);
		TABLE_COLUMNS_MAP.put("outputParameters", Types.CLOB);
		TABLE_COLUMNS_MAP.put("replyTo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workflowDefinitionLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FulfilmentRequest (mvccVersion LONG default 0 not null,externalReferenceCode VARCHAR(75) null,fulfilmentRequestId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,endDate DATE null,originalFulfilmentRequest TEXT null,inputParameters TEXT null,outputParameters TEXT null,replyTo VARCHAR(75) null,startDate DATE null,type_ VARCHAR(75) null,workflowDefinitionLinkId LONG,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table FulfilmentRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fulfilmentRequest.fulfilmentRequestId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FulfilmentRequest.fulfilmentRequestId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FULFILMENTREQUESTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static FulfilmentRequest toModel(FulfilmentRequestSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FulfilmentRequest model = new FulfilmentRequestImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setExternalReferenceCode(soapModel.getExternalReferenceCode());
		model.setFulfilmentRequestId(soapModel.getFulfilmentRequestId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEndDate(soapModel.getEndDate());
		model.setOriginalFulfilmentRequest(
			soapModel.getOriginalFulfilmentRequest());
		model.setInputParameters(soapModel.getInputParameters());
		model.setOutputParameters(soapModel.getOutputParameters());
		model.setReplyTo(soapModel.getReplyTo());
		model.setStartDate(soapModel.getStartDate());
		model.setType(soapModel.getType());
		model.setWorkflowDefinitionLinkId(
			soapModel.getWorkflowDefinitionLinkId());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<FulfilmentRequest> toModels(
		FulfilmentRequestSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<FulfilmentRequest> models = new ArrayList<FulfilmentRequest>(
			soapModels.length);

		for (FulfilmentRequestSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public FulfilmentRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fulfilmentRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFulfilmentRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fulfilmentRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FulfilmentRequest.class;
	}

	@Override
	public String getModelClassName() {
		return FulfilmentRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FulfilmentRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FulfilmentRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FulfilmentRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FulfilmentRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FulfilmentRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FulfilmentRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FulfilmentRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FulfilmentRequest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FulfilmentRequest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, FulfilmentRequest>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			FulfilmentRequest.class.getClassLoader(), FulfilmentRequest.class,
			ModelWrapper.class);

		try {
			Constructor<FulfilmentRequest> constructor =
				(Constructor<FulfilmentRequest>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<FulfilmentRequest, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FulfilmentRequest, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FulfilmentRequest, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FulfilmentRequest, Object>>();
		Map<String, BiConsumer<FulfilmentRequest, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FulfilmentRequest, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", FulfilmentRequest::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<FulfilmentRequest, Long>)
				FulfilmentRequest::setMvccVersion);
		attributeGetterFunctions.put(
			"externalReferenceCode",
			FulfilmentRequest::getExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<FulfilmentRequest, String>)
				FulfilmentRequest::setExternalReferenceCode);
		attributeGetterFunctions.put(
			"fulfilmentRequestId", FulfilmentRequest::getFulfilmentRequestId);
		attributeSetterBiConsumers.put(
			"fulfilmentRequestId",
			(BiConsumer<FulfilmentRequest, Long>)
				FulfilmentRequest::setFulfilmentRequestId);
		attributeGetterFunctions.put(
			"companyId", FulfilmentRequest::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FulfilmentRequest, Long>)
				FulfilmentRequest::setCompanyId);
		attributeGetterFunctions.put("userId", FulfilmentRequest::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FulfilmentRequest, Long>)FulfilmentRequest::setUserId);
		attributeGetterFunctions.put(
			"userName", FulfilmentRequest::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FulfilmentRequest, String>)
				FulfilmentRequest::setUserName);
		attributeGetterFunctions.put(
			"createDate", FulfilmentRequest::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FulfilmentRequest, Date>)
				FulfilmentRequest::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FulfilmentRequest::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FulfilmentRequest, Date>)
				FulfilmentRequest::setModifiedDate);
		attributeGetterFunctions.put("endDate", FulfilmentRequest::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate",
			(BiConsumer<FulfilmentRequest, Date>)FulfilmentRequest::setEndDate);
		attributeGetterFunctions.put(
			"originalFulfilmentRequest",
			FulfilmentRequest::getOriginalFulfilmentRequest);
		attributeSetterBiConsumers.put(
			"originalFulfilmentRequest",
			(BiConsumer<FulfilmentRequest, String>)
				FulfilmentRequest::setOriginalFulfilmentRequest);
		attributeGetterFunctions.put(
			"inputParameters", FulfilmentRequest::getInputParameters);
		attributeSetterBiConsumers.put(
			"inputParameters",
			(BiConsumer<FulfilmentRequest, String>)
				FulfilmentRequest::setInputParameters);
		attributeGetterFunctions.put(
			"outputParameters", FulfilmentRequest::getOutputParameters);
		attributeSetterBiConsumers.put(
			"outputParameters",
			(BiConsumer<FulfilmentRequest, String>)
				FulfilmentRequest::setOutputParameters);
		attributeGetterFunctions.put("replyTo", FulfilmentRequest::getReplyTo);
		attributeSetterBiConsumers.put(
			"replyTo",
			(BiConsumer<FulfilmentRequest, String>)
				FulfilmentRequest::setReplyTo);
		attributeGetterFunctions.put(
			"startDate", FulfilmentRequest::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate",
			(BiConsumer<FulfilmentRequest, Date>)
				FulfilmentRequest::setStartDate);
		attributeGetterFunctions.put("type", FulfilmentRequest::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<FulfilmentRequest, String>)FulfilmentRequest::setType);
		attributeGetterFunctions.put(
			"workflowDefinitionLinkId",
			FulfilmentRequest::getWorkflowDefinitionLinkId);
		attributeSetterBiConsumers.put(
			"workflowDefinitionLinkId",
			(BiConsumer<FulfilmentRequest, Long>)
				FulfilmentRequest::setWorkflowDefinitionLinkId);
		attributeGetterFunctions.put("status", FulfilmentRequest::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<FulfilmentRequest, Integer>)
				FulfilmentRequest::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", FulfilmentRequest::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<FulfilmentRequest, Long>)
				FulfilmentRequest::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", FulfilmentRequest::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<FulfilmentRequest, String>)
				FulfilmentRequest::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", FulfilmentRequest::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<FulfilmentRequest, Date>)
				FulfilmentRequest::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getFulfilmentRequestId() {
		return _fulfilmentRequestId;
	}

	@Override
	public void setFulfilmentRequestId(long fulfilmentRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fulfilmentRequestId = fulfilmentRequestId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public String getOriginalFulfilmentRequest() {
		if (_originalFulfilmentRequest == null) {
			return "";
		}
		else {
			return _originalFulfilmentRequest;
		}
	}

	@Override
	public void setOriginalFulfilmentRequest(String originalFulfilmentRequest) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_originalFulfilmentRequest = originalFulfilmentRequest;
	}

	@JSON
	@Override
	public String getInputParameters() {
		if (_inputParameters == null) {
			return "";
		}
		else {
			return _inputParameters;
		}
	}

	@Override
	public void setInputParameters(String inputParameters) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_inputParameters = inputParameters;
	}

	@JSON
	@Override
	public String getOutputParameters() {
		if (_outputParameters == null) {
			return "";
		}
		else {
			return _outputParameters;
		}
	}

	@Override
	public void setOutputParameters(String outputParameters) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_outputParameters = outputParameters;
	}

	@JSON
	@Override
	public String getReplyTo() {
		if (_replyTo == null) {
			return "";
		}
		else {
			return _replyTo;
		}
	}

	@Override
	public void setReplyTo(String replyTo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_replyTo = replyTo;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@JSON
	@Override
	public long getWorkflowDefinitionLinkId() {
		return _workflowDefinitionLinkId;
	}

	@Override
	public void setWorkflowDefinitionLinkId(long workflowDefinitionLinkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowDefinitionLinkId = workflowDefinitionLinkId;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FulfilmentRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FulfilmentRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FulfilmentRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FulfilmentRequestImpl fulfilmentRequestImpl =
			new FulfilmentRequestImpl();

		fulfilmentRequestImpl.setMvccVersion(getMvccVersion());
		fulfilmentRequestImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		fulfilmentRequestImpl.setFulfilmentRequestId(getFulfilmentRequestId());
		fulfilmentRequestImpl.setCompanyId(getCompanyId());
		fulfilmentRequestImpl.setUserId(getUserId());
		fulfilmentRequestImpl.setUserName(getUserName());
		fulfilmentRequestImpl.setCreateDate(getCreateDate());
		fulfilmentRequestImpl.setModifiedDate(getModifiedDate());
		fulfilmentRequestImpl.setEndDate(getEndDate());
		fulfilmentRequestImpl.setOriginalFulfilmentRequest(
			getOriginalFulfilmentRequest());
		fulfilmentRequestImpl.setInputParameters(getInputParameters());
		fulfilmentRequestImpl.setOutputParameters(getOutputParameters());
		fulfilmentRequestImpl.setReplyTo(getReplyTo());
		fulfilmentRequestImpl.setStartDate(getStartDate());
		fulfilmentRequestImpl.setType(getType());
		fulfilmentRequestImpl.setWorkflowDefinitionLinkId(
			getWorkflowDefinitionLinkId());
		fulfilmentRequestImpl.setStatus(getStatus());
		fulfilmentRequestImpl.setStatusByUserId(getStatusByUserId());
		fulfilmentRequestImpl.setStatusByUserName(getStatusByUserName());
		fulfilmentRequestImpl.setStatusDate(getStatusDate());

		fulfilmentRequestImpl.resetOriginalValues();

		return fulfilmentRequestImpl;
	}

	@Override
	public FulfilmentRequest cloneWithOriginalValues() {
		FulfilmentRequestImpl fulfilmentRequestImpl =
			new FulfilmentRequestImpl();

		fulfilmentRequestImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		fulfilmentRequestImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		fulfilmentRequestImpl.setFulfilmentRequestId(
			this.<Long>getColumnOriginalValue("fulfilmentRequestId"));
		fulfilmentRequestImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		fulfilmentRequestImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		fulfilmentRequestImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		fulfilmentRequestImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		fulfilmentRequestImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		fulfilmentRequestImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));
		fulfilmentRequestImpl.setOriginalFulfilmentRequest(
			this.<String>getColumnOriginalValue("originalFulfilmentRequest"));
		fulfilmentRequestImpl.setInputParameters(
			this.<String>getColumnOriginalValue("inputParameters"));
		fulfilmentRequestImpl.setOutputParameters(
			this.<String>getColumnOriginalValue("outputParameters"));
		fulfilmentRequestImpl.setReplyTo(
			this.<String>getColumnOriginalValue("replyTo"));
		fulfilmentRequestImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		fulfilmentRequestImpl.setType(
			this.<String>getColumnOriginalValue("type_"));
		fulfilmentRequestImpl.setWorkflowDefinitionLinkId(
			this.<Long>getColumnOriginalValue("workflowDefinitionLinkId"));
		fulfilmentRequestImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		fulfilmentRequestImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		fulfilmentRequestImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		fulfilmentRequestImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return fulfilmentRequestImpl;
	}

	@Override
	public int compareTo(FulfilmentRequest fulfilmentRequest) {
		int value = 0;

		if (getFulfilmentRequestId() <
				fulfilmentRequest.getFulfilmentRequestId()) {

			value = -1;
		}
		else if (getFulfilmentRequestId() >
					fulfilmentRequest.getFulfilmentRequestId()) {

			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FulfilmentRequest)) {
			return false;
		}

		FulfilmentRequest fulfilmentRequest = (FulfilmentRequest)object;

		long primaryKey = fulfilmentRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FulfilmentRequest> toCacheModel() {
		FulfilmentRequestCacheModel fulfilmentRequestCacheModel =
			new FulfilmentRequestCacheModel();

		fulfilmentRequestCacheModel.mvccVersion = getMvccVersion();

		fulfilmentRequestCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			fulfilmentRequestCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			fulfilmentRequestCacheModel.externalReferenceCode = null;
		}

		fulfilmentRequestCacheModel.fulfilmentRequestId =
			getFulfilmentRequestId();

		fulfilmentRequestCacheModel.companyId = getCompanyId();

		fulfilmentRequestCacheModel.userId = getUserId();

		fulfilmentRequestCacheModel.userName = getUserName();

		String userName = fulfilmentRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			fulfilmentRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			fulfilmentRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			fulfilmentRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fulfilmentRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			fulfilmentRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			fulfilmentRequestCacheModel.endDate = endDate.getTime();
		}
		else {
			fulfilmentRequestCacheModel.endDate = Long.MIN_VALUE;
		}

		fulfilmentRequestCacheModel.originalFulfilmentRequest =
			getOriginalFulfilmentRequest();

		String originalFulfilmentRequest =
			fulfilmentRequestCacheModel.originalFulfilmentRequest;

		if ((originalFulfilmentRequest != null) &&
			(originalFulfilmentRequest.length() == 0)) {

			fulfilmentRequestCacheModel.originalFulfilmentRequest = null;
		}

		fulfilmentRequestCacheModel.inputParameters = getInputParameters();

		String inputParameters = fulfilmentRequestCacheModel.inputParameters;

		if ((inputParameters != null) && (inputParameters.length() == 0)) {
			fulfilmentRequestCacheModel.inputParameters = null;
		}

		fulfilmentRequestCacheModel.outputParameters = getOutputParameters();

		String outputParameters = fulfilmentRequestCacheModel.outputParameters;

		if ((outputParameters != null) && (outputParameters.length() == 0)) {
			fulfilmentRequestCacheModel.outputParameters = null;
		}

		fulfilmentRequestCacheModel.replyTo = getReplyTo();

		String replyTo = fulfilmentRequestCacheModel.replyTo;

		if ((replyTo != null) && (replyTo.length() == 0)) {
			fulfilmentRequestCacheModel.replyTo = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			fulfilmentRequestCacheModel.startDate = startDate.getTime();
		}
		else {
			fulfilmentRequestCacheModel.startDate = Long.MIN_VALUE;
		}

		fulfilmentRequestCacheModel.type = getType();

		String type = fulfilmentRequestCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			fulfilmentRequestCacheModel.type = null;
		}

		fulfilmentRequestCacheModel.workflowDefinitionLinkId =
			getWorkflowDefinitionLinkId();

		fulfilmentRequestCacheModel.status = getStatus();

		fulfilmentRequestCacheModel.statusByUserId = getStatusByUserId();

		fulfilmentRequestCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = fulfilmentRequestCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			fulfilmentRequestCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			fulfilmentRequestCacheModel.statusDate = statusDate.getTime();
		}
		else {
			fulfilmentRequestCacheModel.statusDate = Long.MIN_VALUE;
		}

		return fulfilmentRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FulfilmentRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FulfilmentRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FulfilmentRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FulfilmentRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FulfilmentRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FulfilmentRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FulfilmentRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FulfilmentRequest)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FulfilmentRequest>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private String _externalReferenceCode;
	private long _fulfilmentRequestId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _endDate;
	private String _originalFulfilmentRequest;
	private String _inputParameters;
	private String _outputParameters;
	private String _replyTo;
	private Date _startDate;
	private String _type;
	private long _workflowDefinitionLinkId;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FulfilmentRequest, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FulfilmentRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("fulfilmentRequestId", _fulfilmentRequestId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put(
			"originalFulfilmentRequest", _originalFulfilmentRequest);
		_columnOriginalValues.put("inputParameters", _inputParameters);
		_columnOriginalValues.put("outputParameters", _outputParameters);
		_columnOriginalValues.put("replyTo", _replyTo);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put(
			"workflowDefinitionLinkId", _workflowDefinitionLinkId);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("fulfilmentRequestId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("endDate", 256L);

		columnBitmasks.put("originalFulfilmentRequest", 512L);

		columnBitmasks.put("inputParameters", 1024L);

		columnBitmasks.put("outputParameters", 2048L);

		columnBitmasks.put("replyTo", 4096L);

		columnBitmasks.put("startDate", 8192L);

		columnBitmasks.put("type_", 16384L);

		columnBitmasks.put("workflowDefinitionLinkId", 32768L);

		columnBitmasks.put("status", 65536L);

		columnBitmasks.put("statusByUserId", 131072L);

		columnBitmasks.put("statusByUserName", 262144L);

		columnBitmasks.put("statusDate", 524288L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FulfilmentRequest _escapedModel;

}