/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

const DEFAULT_LABEL = {
	DATA_SET: 'Sample Data Set',
};

const REL_PREFIX = 'r_fdsViewFDS';
const REL_POSTFIX = 'Relationship_c_fdsViewERC';

const CARDS_SECTION_DATA_SET_RELATIONSHIP =
	REL_PREFIX + 'CardsSection' + REL_POSTFIX;
const LIST_SECTION_DATA_SET_RELATIONSHIP =
	REL_PREFIX + 'ListSection' + REL_POSTFIX;
const TABLE_SECTION_DATA_SET_RELATIONSHIP = REL_PREFIX + 'Field' + REL_POSTFIX;

const CREATION_ACTION_DATA_SET_RELATIONSHIP =
	REL_PREFIX + 'CreationAction' + REL_POSTFIX;
const ITEM_ACTION_DATA_SET_RELATIONSHIP =
	REL_PREFIX + 'ItemAction' + REL_POSTFIX;

const CLIENT_EXTENSION_FILTER_DATA_SET_RELATIONSHIP =
	REL_PREFIX + 'ClientExtensionFilter_c_fdsViewId';
const DATE_FILTER_DATA_SET_RELATIONSHIP =
	REL_PREFIX + 'DateFilter' + REL_POSTFIX;
const SELECTION_FILTER_DATA_SET_RELATIONSHIP =
	REL_PREFIX + 'DynamicFilter' + REL_POSTFIX;

const SORT_DATA_SET_RELATIONSHIP = REL_PREFIX + 'Sort' + REL_POSTFIX;

export {
	CARDS_SECTION_DATA_SET_RELATIONSHIP,
	CLIENT_EXTENSION_FILTER_DATA_SET_RELATIONSHIP,
	LIST_SECTION_DATA_SET_RELATIONSHIP,
	TABLE_SECTION_DATA_SET_RELATIONSHIP,
	CREATION_ACTION_DATA_SET_RELATIONSHIP,
	ITEM_ACTION_DATA_SET_RELATIONSHIP,
	DATE_FILTER_DATA_SET_RELATIONSHIP,
	SELECTION_FILTER_DATA_SET_RELATIONSHIP,
	SORT_DATA_SET_RELATIONSHIP,
	DEFAULT_LABEL,
};
