##
## Test Suites
##

    modified.files.includes[relevant][iframe-rule]=**

    relevant.rule.names=\
        iframe-rule

    test.batch.names[relevant][iframe-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][iframe-rule]=\
        apps/iframe/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][iframe-rule]=\
        apps/iframe/**/*Test.java

##
## Testray
##

    testray.main.component.name=IFrame Portlet